### ISSUE TITLE
Question: why pack this into msi 

### ISSUE THREAD

**Issue by medic17** [ciao1092/IELauncher#1]
What is the advantage of packing this into an msi instead of a stand alone executable. Just trying to learn

**Comment by ciao1092** [comment]
Nothing, it's just to install it for multiple users.
The exe gets installed in Program Files, and every user gets a shortcut in the start menu programs list

**Comment by ciao1092** [comment]
Anyway, I'll upload somewhen in the future a standalone version, like you did

**Comment by ciao1092** [comment]
Done. (see releases section or the readme of the project, I included a standalone version, which should work without installing .net core and doesn't need installing)

**Comment by MichalisDBA** [comment]
@ciao1092 Thanks for this but why the standalone version is 139MB? 139MB to open internet explorer?

**Comment by ciao1092** [comment]
The standalone version packs the whole .NET
